packages:
  - artifacts/*
  - lib/*
  - lib/integrations/*
  - scripts

autoInstallPeers: false

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@pnpm/exe'
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver
