import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const dir = dirname(fileURLToPath(import.meta.url));
const parts = readdirSync(dir).filter((n) => n.startsWith("chat.ts.part.")).sort();
const b64 = parts.map((n) => readFileSync(join(dir, n), "utf8")).join("");
const buf = gunzipSync(Buffer.from(b64, "base64"));
writeFileSync(join(dir, "chat.ts"), buf);
console.log("restored chat.ts", buf.length, "bytes");
