const colors = {
  light: {
    text: '#202124',
    tint: '#3B8FD6',
    background: '#F1F2F5',
    foreground: '#202124',
    card: '#FFFFFF',
    cardForeground: '#202124',
    primary: '#3B8FD6',
    primaryForeground: '#FFFFFF',
    secondary: '#EAF6FF',
    secondaryForeground: '#202124',
    muted: '#E8EAED',
    mutedForeground: '#70757D',
    accent: '#63BFFB',
    accentForeground: '#FFFFFF',
    destructive: '#D94C5C',
    destructiveForeground: '#FFFFFF',
    border: '#DDE1E6',
    input: '#DDE1E6',
  },
  dark: {
    text: '#F5F7FA',
    tint: '#63BFFB',
    background: '#16202A',
    foreground: '#F5F7FA',
    card: '#1D2A36',
    cardForeground: '#F5F7FA',
    primary: '#63BFFB',
    primaryForeground: '#FFFFFF',
    secondary: '#182A36',
    secondaryForeground: '#F5F7FA',
    muted: '#263744',
    mutedForeground: '#A6B2BC',
    accent: '#63BFFB',
    accentForeground: '#FFFFFF',
    destructive: '#F06A79',
    destructiveForeground: '#FFFFFF',
    border: '#324552',
    input: '#324552',
  },
  radius: 10,
};

export default colors;
