// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/old-time/OldTimeMobileTour.tsx": () => import("../components/mockups/old-time/OldTimeMobileTour.tsx"),
  "./components/mockups/whatsapp-home/Current.tsx": () => import("../components/mockups/whatsapp-home/Current.tsx"),
  "./components/mockups/whatsapp-home/WhatsAppHome.tsx": () => import("../components/mockups/whatsapp-home/WhatsAppHome.tsx")
};
