// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/old-time-theme/Interior.tsx": () => import("../components/mockups/old-time-theme/Interior.tsx")
};
