CREATE TABLE "chat_auth_challenges" ("id" text PRIMARY KEY NOT NULL, "phone" text NOT NULL, "code_hash" text, "request_ip_hash" text NOT NULL, "status" text DEFAULT 'pending' NOT NULL, "attempt_count" integer DEFAULT 0 NOT NULL, "created_at" bigint NOT NULL, "expires_at" bigint NOT NULL, "last_attempt_at" bigint);
CREATE TABLE "chat_auth_sessions" ("id" text PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "token_hash" text NOT NULL, "created_at" bigint NOT NULL, "expires_at" bigint NOT NULL, "revoked_at" bigint, "last_seen_at" bigint NOT NULL);
CREATE TABLE "chat_participants" ("chat_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "chat_participants_chat_id_user_id_pk" PRIMARY KEY("chat_id","user_id"));
CREATE TABLE "chat_chats" ("id" serial PRIMARY KEY NOT NULL, "is_group" boolean DEFAULT false NOT NULL, "name" text DEFAULT '' NOT NULL, "created_at" bigint NOT NULL);
CREATE TABLE "chat_messages" ("id" serial PRIMARY KEY NOT NULL, "chat_id" integer NOT NULL, "sender_id" integer NOT NULL, "content" text DEFAULT '' NOT NULL, "attachment" jsonb, "timestamp" bigint NOT NULL, "read" boolean DEFAULT false NOT NULL, "opened_at" bigint, "expires_at" bigint, "saved" boolean DEFAULT false NOT NULL);
CREATE TABLE "chat_upload_slots" ("id" text PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "object_path" text NOT NULL, "content_type" text NOT NULL, "declared_size" integer NOT NULL, "status" text DEFAULT 'issued' NOT NULL, "created_at" bigint NOT NULL, "expires_at" bigint NOT NULL, "message_id" integer, "reference_type" text, "reference_id" integer);
CREATE TABLE "chat_users" ("id" serial PRIMARY KEY NOT NULL, "phone" text NOT NULL, "name" text NOT NULL, "online" boolean DEFAULT false NOT NULL, "last_seen" bigint NOT NULL, CONSTRAINT "chat_users_phone_unique" UNIQUE("phone"));
CREATE TABLE "social_blocks" ("blocker_id" integer NOT NULL, "blocked_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_blocks_blocker_id_blocked_id_pk" PRIMARY KEY("blocker_id","blocked_id"));
CREATE TABLE "social_close_friends" ("owner_id" integer NOT NULL, "member_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_close_friends_owner_id_member_id_pk" PRIMARY KEY("owner_id","member_id"));
CREATE TABLE "social_comment_likes" ("comment_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_comment_likes_comment_id_user_id_pk" PRIMARY KEY("comment_id","user_id"));
CREATE TABLE "social_comments" ("id" serial PRIMARY KEY NOT NULL, "post_id" integer NOT NULL, "author_id" integer NOT NULL, "parent_id" integer, "content" text NOT NULL, "created_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "social_follows" ("follower_id" integer NOT NULL, "following_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_follows_follower_id_following_id_pk" PRIMARY KEY("follower_id","following_id"));
CREATE TABLE "social_highlight_items" ("highlight_id" integer NOT NULL, "story_id" integer NOT NULL, "added_at" bigint NOT NULL, CONSTRAINT "social_highlight_items_highlight_id_story_id_pk" PRIMARY KEY("highlight_id","story_id"));
CREATE TABLE "social_highlights" ("id" serial PRIMARY KEY NOT NULL, "owner_id" integer NOT NULL, "title" text NOT NULL, "cover_object_path" text, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "social_mutes" ("muter_id" integer NOT NULL, "muted_user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_mutes_muter_id_muted_user_id_pk" PRIMARY KEY("muter_id","muted_user_id"));
CREATE TABLE "social_notifications" ("id" serial PRIMARY KEY NOT NULL, "recipient_id" integer NOT NULL, "actor_id" integer NOT NULL, "type" text NOT NULL, "story_id" integer, "reply_id" integer, "created_at" bigint NOT NULL, "read_at" bigint);
CREATE TABLE "social_post_likes" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_post_likes_post_id_user_id_pk" PRIMARY KEY("post_id","user_id"));
CREATE TABLE "social_post_reposts" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_post_reposts_post_id_user_id_pk" PRIMARY KEY("post_id","user_id"));
CREATE TABLE "social_post_saves" ("post_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_post_saves_post_id_user_id_pk" PRIMARY KEY("post_id","user_id"));
CREATE TABLE "social_posts" ("id" serial PRIMARY KEY NOT NULL, "author_id" integer NOT NULL, "kind" text DEFAULT 'text' NOT NULL, "content" text DEFAULT '' NOT NULL, "visibility" text DEFAULT 'friends' NOT NULL, "media" jsonb, "link_url" text, "link_title" text, "link_description" text, "link_image_url" text, "news_source" text, "news_published_at" bigint, "news_url" text, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "social_reports" ("id" serial PRIMARY KEY NOT NULL, "reporter_id" integer NOT NULL, "target_type" text NOT NULL, "target_id" integer NOT NULL, "reason" text NOT NULL, "details" text DEFAULT '' NOT NULL, "created_at" bigint NOT NULL);
CREATE TABLE "social_sharing_exclusions" ("owner_id" integer NOT NULL, "excluded_user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_sharing_exclusions_owner_id_excluded_user_id_pk" PRIMARY KEY("owner_id","excluded_user_id"));
CREATE TABLE "social_stories" ("id" serial PRIMARY KEY NOT NULL, "author_id" integer NOT NULL, "kind" text DEFAULT 'text' NOT NULL, "content" text DEFAULT '' NOT NULL, "visibility" text DEFAULT 'friends' NOT NULL, "media" jsonb, "created_at" bigint NOT NULL, "expires_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "social_story_reactions" ("story_id" integer NOT NULL, "user_id" integer NOT NULL, "reaction" text NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "social_story_reactions_story_id_user_id_pk" PRIMARY KEY("story_id","user_id"));
CREATE TABLE "social_story_replies" ("id" serial PRIMARY KEY NOT NULL, "story_id" integer NOT NULL, "author_id" integer NOT NULL, "content" text NOT NULL, "created_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "social_story_viewers" ("story_id" integer NOT NULL, "viewer_id" integer NOT NULL, "viewed_at" bigint NOT NULL, CONSTRAINT "social_story_viewers_story_id_viewer_id_pk" PRIMARY KEY("story_id","viewer_id"));
CREATE TABLE "map_pin_comments" ("id" serial PRIMARY KEY NOT NULL, "pin_id" integer NOT NULL, "author_id" integer NOT NULL, "content" text NOT NULL, "created_at" bigint NOT NULL, "deleted" boolean DEFAULT false NOT NULL);
CREATE TABLE "map_pin_reactions" ("pin_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "map_pin_reactions_pin_id_user_id_pk" PRIMARY KEY("pin_id","user_id"));
CREATE TABLE "map_pin_reports" ("id" serial PRIMARY KEY NOT NULL, "pin_id" integer NOT NULL, "reporter_id" integer NOT NULL, "reason" text NOT NULL, "created_at" bigint NOT NULL);
CREATE TABLE "map_pin_saves" ("pin_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "map_pin_saves_pin_id_user_id_pk" PRIMARY KEY("pin_id","user_id"));
CREATE TABLE "map_pins" ("id" serial PRIMARY KEY NOT NULL, "author_id" integer NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "caption" text, "visibility" text DEFAULT 'friends' NOT NULL, "created_at" bigint NOT NULL, "updated_at" bigint NOT NULL, "expires_at" bigint, "deleted" boolean DEFAULT false NOT NULL);
CREATE INDEX "chat_auth_challenges_phone_created_idx" ON "chat_auth_challenges" ("phone","created_at");
CREATE INDEX "chat_auth_challenges_ip_created_idx" ON "chat_auth_challenges" ("request_ip_hash","created_at");
CREATE INDEX "chat_auth_challenges_expiry_idx" ON "chat_auth_challenges" ("expires_at");
CREATE UNIQUE INDEX "chat_auth_sessions_token_hash_idx" ON "chat_auth_sessions" ("token_hash");
CREATE INDEX "chat_auth_sessions_user_expiry_idx" ON "chat_auth_sessions" ("user_id","expires_at");
CREATE UNIQUE INDEX "chat_upload_slots_object_path_idx" ON "chat_upload_slots" ("object_path");
CREATE INDEX "chat_upload_slots_expiry_status_idx" ON "chat_upload_slots" ("expires_at","status");
CREATE INDEX "social_blocks_blocked_idx" ON "social_blocks" ("blocked_id");
CREATE INDEX "social_close_friends_member_idx" ON "social_close_friends" ("member_id");
CREATE INDEX "social_comments_post_created_idx" ON "social_comments" ("post_id","created_at");
CREATE INDEX "social_comments_parent_idx" ON "social_comments" ("parent_id");
CREATE INDEX "social_follows_following_idx" ON "social_follows" ("following_id");
CREATE INDEX "social_highlight_items_story_idx" ON "social_highlight_items" ("story_id");
CREATE INDEX "social_highlights_owner_updated_idx" ON "social_highlights" ("owner_id","updated_at");
CREATE INDEX "social_notifications_recipient_created_idx" ON "social_notifications" ("recipient_id","created_at");
CREATE INDEX "social_notifications_story_idx" ON "social_notifications" ("story_id");
CREATE INDEX "social_post_likes_user_idx" ON "social_post_likes" ("user_id");
CREATE INDEX "social_post_reposts_user_idx" ON "social_post_reposts" ("user_id");
CREATE INDEX "social_post_saves_user_idx" ON "social_post_saves" ("user_id");
CREATE INDEX "social_posts_author_created_idx" ON "social_posts" ("author_id","created_at");
CREATE INDEX "social_posts_feed_idx" ON "social_posts" ("created_at","deleted");
CREATE INDEX "social_posts_news_idx" ON "social_posts" ("news_url");
CREATE UNIQUE INDEX "social_reports_reporter_target_idx" ON "social_reports" ("reporter_id","target_type","target_id");
CREATE INDEX "social_reports_target_idx" ON "social_reports" ("target_type","target_id");
CREATE INDEX "social_sharing_exclusions_excluded_idx" ON "social_sharing_exclusions" ("excluded_user_id");
CREATE INDEX "social_stories_audience_idx" ON "social_stories" ("deleted","expires_at","created_at");
CREATE INDEX "social_stories_author_created_idx" ON "social_stories" ("author_id","created_at");
CREATE INDEX "social_story_reactions_user_idx" ON "social_story_reactions" ("user_id");
CREATE INDEX "social_story_replies_story_created_idx" ON "social_story_replies" ("story_id","created_at");
CREATE INDEX "social_story_replies_author_idx" ON "social_story_replies" ("author_id");
CREATE INDEX "social_story_viewers_viewer_idx" ON "social_story_viewers" ("viewer_id");
CREATE INDEX "map_pin_comments_pin_idx" ON "map_pin_comments" ("pin_id","created_at");
CREATE UNIQUE INDEX "map_pin_reports_reporter_pin_idx" ON "map_pin_reports" ("reporter_id","pin_id");
CREATE INDEX "map_pin_saves_user_idx" ON "map_pin_saves" ("user_id");
CREATE INDEX "map_pins_active_idx" ON "map_pins" ("deleted","expires_at","created_at");
CREATE INDEX "map_pins_author_idx" ON "map_pins" ("author_id","created_at");