-- Ensure the staging schema exists (idempotent with the earlier migration).
CREATE SCHEMA IF NOT EXISTS old_time;

-- Lightweight public.profiles extension used by existing Supabase auth surfaces.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS display_name text;

CREATE TABLE IF NOT EXISTS old_time.discovery_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform text NOT NULL,
  canonical_url text NOT NULL,
  embed_html text NOT NULL,
  title text NOT NULL,
  creator_name text NOT NULL,
  creator_handle text,
  category text,
  engagement jsonb NOT NULL DEFAULT '{}'::jsonb,
  latitude double precision,
  longitude double precision,
  location_label text,
  published_at bigint,
  discovered_at bigint NOT NULL,
  status text NOT NULL DEFAULT 'active'
);

CREATE UNIQUE INDEX IF NOT EXISTS old_time_discovery_items_url_idx
  ON old_time.discovery_items (canonical_url);
CREATE INDEX IF NOT EXISTS old_time_discovery_items_location_idx
  ON old_time.discovery_items (latitude, longitude);
CREATE INDEX IF NOT EXISTS old_time_discovery_items_status_date_idx
  ON old_time.discovery_items (status, discovered_at);

CREATE TABLE IF NOT EXISTS old_time.discovery_creator_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES old_time.discovery_items(id) ON DELETE CASCADE,
  claimant_id integer NOT NULL,
  note text,
  status text NOT NULL DEFAULT 'pending',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS old_time_discovery_claims_claimant_item_idx
  ON old_time.discovery_creator_claims (claimant_id, item_id);
CREATE INDEX IF NOT EXISTS old_time_discovery_claims_item_status_idx
  ON old_time.discovery_creator_claims (item_id, status);

ALTER TABLE old_time.discovery_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE old_time.discovery_creator_claims ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON old_time.discovery_items FROM anon, authenticated;
REVOKE ALL ON old_time.discovery_creator_claims FROM anon, authenticated;
